"""
ai/schemas/strategy.py
======================
Strategy candidate and evaluation models.
All payoff values are calculated by the Python quant engine — never by the LLM.
"""
from __future__ import annotations
from typing import Optional
from pydantic import BaseModel, Field


# Valid strategy type identifiers
STRATEGY_TYPES = [
    "bull_put_spread",
    "bear_call_spread",
    "bull_call_spread",
    "bear_put_spread",
    "iron_condor",
    "iron_fly",
    "long_straddle",
    "short_strangle",
]


class StrategyLeg(BaseModel):
    """One leg of a multi-leg option strategy."""
    action: str = Field(..., description="BUY | SELL")
    option_type: str = Field(..., description="CE | PE")
    strike: float
    symbol: str = Field("", description="Full option symbol — must exist in chain snapshot")
    ltp: float = Field(0.0, description="LTP at time of strategy generation")
    bid: float = Field(0.0)
    ask: float = Field(0.0)
    delta: float = Field(0.0)
    gamma: float = Field(0.0)
    theta: float = Field(0.0)
    vega: float = Field(0.0)
    iv: float = Field(0.0)
    oi: int = Field(0, description="Open interest — used for liquidity filtering")
    lot_size: int = Field(0)
    # Offset relative to ATM (e.g. "OTM2", "ATM", "ITM1") for optionsmultiorder
    atm_offset: str = Field("", description="Offset string for OpenAlgo optionsmultiorder API")


class PayoffResult(BaseModel):
    """Deterministic payoff calculation result for one strategy."""
    entry_credit: float = Field(0.0, description="Net credit received (positive) or debit paid (negative)")
    max_profit: float = Field(0.0, description="Maximum possible profit in points")
    max_loss: float = Field(0.0, description="Maximum possible loss in points (positive number)")
    breakeven_lower: Optional[float] = Field(None, description="Lower breakeven price")
    breakeven_upper: Optional[float] = Field(None, description="Upper breakeven price (for two-sided strategies)")
    risk_reward_ratio: float = Field(0.0, description="max_profit / max_loss")
    probability_profit: float = Field(0.0, description="Estimated probability of profit at expiry (delta-based)")
    margin_required: float = Field(0.0, description="Estimated margin requirement in ₹")
    net_delta: float = Field(0.0, description="Portfolio-level net delta")
    net_theta: float = Field(0.0, description="Portfolio-level net daily theta")
    net_vega: float = Field(0.0, description="Portfolio-level net vega")
    slippage_estimate: float = Field(0.0, description="Estimated total slippage in points")
    liquidity_score: float = Field(0.0, description="0-100 liquidity score based on bid/ask and OI")


class StrategyCandidate(BaseModel):
    """
    A fully-specified option strategy candidate.
    Generated by the Python strategy engine from the chain snapshot.
    All strikes must be verified to exist in the chain before creation.
    """
    strategy_type: str = Field(..., description="One of STRATEGY_TYPES")
    underlying: str
    expiry_date: str
    legs: list[StrategyLeg]
    payoff: PayoffResult
    regime_aligned: bool = Field(False, description="True if strategy aligns with current regime")
    lot_count: int = Field(1, description="Number of lots")

    def total_premium_collected(self) -> float:
        """Net premium in ₹ for 1 lot."""
        return self.payoff.entry_credit * self.legs[0].lot_size if self.legs else 0.0


class ScoreBreakdown(BaseModel):
    """Per-factor score breakdown for transparency."""
    trend_alignment: float = 0.0
    oi_structure: float = 0.0
    risk_reward: float = 0.0
    iv_environment: float = 0.0
    probability_metrics: float = 0.0
    liquidity: float = 0.0
    expected_move_alignment: float = 0.0
    event_risk: float = 0.0
    slippage: float = 0.0
    total: float = 0.0
    effective_weights: dict = Field(default_factory=dict, description="Actual weights used after disabled-component redistribution")


class ScoredCandidate(BaseModel):
    """A strategy candidate with its composite score and breakdown."""
    candidate: StrategyCandidate
    score: float = Field(0.0, description="0-100 composite score")
    score_breakdown: ScoreBreakdown
    rank: int = Field(0, description="1 = best candidate")
    disqualified: bool = Field(False)
    disqualification_reason: str = Field("")
