openalgo:
  apikey: "3b0efae720a743cd0c7d2b9fcffb8eb2cf8832420c214e4746db4568ec80f4f3"
  username: "rahul.tew"
  base_url: "http://127.0.0.1:5000"
  ws_url: "ws://127.0.0.1:8765"

# Equity
exchange: "NSE"
symbols:
  - IOC
  - BANKINDIA
  - PNB
  - RPOWER

timeframes:
  - "5m"
  - "15m"
  #- "30m"

# index/option
index_exchange: "NSE_INDEX"    # Exchange for index data
index_symbols:
  - NIFTY19MAY2623300PE
  - NIFTY19MAY2623300PE
  
index_timeframes:
  - "5m"

# ------------------------------------------------------------
# UT Bot Strategy Parameters
# ------------------------------------------------------------
strategy:
  key_value: 2
  atr_period: 1
  use_heikin_ashi: false

data:
  lookback_days: 5

bot:
  signal_check_interval: 5
  market_open: "09:15"
  market_close: "15:30"
  log_level: "INFO"

ml:
  log_signals: true
  enabled: false
  confidence_threshold: 0.60
  label_lookahead: 5
  win_threshold_pct: 0.3

# ------------------------------------------------------------
# Auto-Trading (Order Placement)
# ------------------------------------------------------------
trading:
  enabled: true
  strategy_name: "UTBot"

  equity:
    enabled: true
    quantity: 1
    product: "CNC"
    price_type: "LIMIT"

  options:
    enabled: true
    quantity: 65
    product: "NRML"
    price_type: "LIMIT"